version: "3"

services:
  neo4j:
    image: "neo4j:4.2.1"
    hostname: webber-jeo4j
    container_name: "webber-jeo4j"
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
