// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNote struct {
	Title    *string `json:"title"`
	Text     string  `json:"text"`
	Citation *string `json:"citation"`
}

type Note struct {
	ID       string  `json:"id"`
	Title    *string `json:"title"`
	Text     *string `json:"text"`
	Citation *string `json:"citation"`
}
